### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by thomas-jeepe** [reasonml-community/bs-webapi-incubator#77] opened 2017-09-16 21:23 UTC
I need to use websocket for the project I am working on, and it is missing from here.

Here is what I am using so far:

```reason
module MessageEvent = {
  type t;
  external data : t => ArrayBuffer.t = "" [@@bs.get];
};

module WebSocket = {
  type t;
  external create_ws : string => t = "WebSocket" [@@bs.new];
  external setBinaryType : t => string => unit = "binaryType" [@@bs.set];
  external onMsg : t => (MessageEvent.t => unit) => unit = "onmessage" [@@bs.set];
  external onOpen : t => (unit => unit) => unit = "onopen" [@@bs.set];
  external send : Uint8Array.t => unit = "" [@@bs.send.pipe : t];
  external onError : t => (unit => unit) => unit = "onerror" [@@bs.set];
  external onClose : t => (unit => unit) => unit = "onclose" [@@bs.set];
  let make url => {
    let ws = create_ws url;
    setBinaryType ws "arraybuffer";
    ws
  };
  let onMsg ws cb => onMsg ws (fun ev => MessageEvent.data ev |> Uint8Array.fromBuffer |> cb);
};
```

This is only designed for a binary use case / mine, its also incredibly incomplete.

I will overtime improve it as necessary for my use case, but otherwise, I am asking what the plan is for this api. I can definitely help write the types for it.

Although I know it isn't in the browser, making a Sink / Stream api from this would make it more pleasant to use. Perhaps taking something from most.js (which I know someone in the discord is making type definitions for).

**Comment by glennsl** [comment] 2017-09-17 10:12
Hi! This project is kind of a dumping ground for incomplete APIs, so it'll fit right in! :smile: Once an API is complete it'll either be upstreamed to bs-platform or separated out into its own project. The bindings should be low-level, but including a high-level API beside it would be fine I think, as long as it doesn't require any outside dependencies (so it can't depend on most.js, but compatibility with it is fine).

A PR for this would be very welcome!

**Comment by thomas-jeepe** [comment] 2017-09-17 18:25
Okay, this definition is super incomplete and only works for binary :D I'll add it in the future when I get websockets worker better (close events, etc.)

**Comment by glennsl** [comment] 2017-12-18 13:49
Closing this as answered. Would love to see a PR!

**Closed by glennsl** 2017-12-18 13:49 UTC
Labels: question

**Comment by keynan** [comment] 2018-03-30 10:19
Has a solution for this emerged in the last 6 months?

**Comment by glennsl** [comment] 2018-03-30 12:07
@keynan See https://redex.github.io/package/bs-websockets

**Comment by keynan** [comment] 2018-03-31 06:05
Thx @glennsl , I've had some trouble getting it to work. I believe the problem is that bs-websockets is a major version behind, and the repository author @cxa has archived the repo.

I don't suppose the @reasonml-community would care to try to take over the official fork. 
Anyway I've tried to upgrade bs-websockets by hand (after the auto upgrader failed), but I'd appreciate an experienced eyes on it:

https://github.com/keynan/bs-websockets/pull/1/files?diff=split

**Comment by glennsl** [comment] 2018-03-31 10:54
Rules for getting a project adopted by reasonml-community is here: https://github.com/reasonml-community/meta. In short, someone needs to volunteer as maintainer and get approved by at least three members.

As an alternative, you might also want to have a look at [bs-socket.io](https://redex.github.io/package/unpublished/reasonml-community/bs-socket.io). That one's already managed by reasonml-community, and is up to date syntactically at least.
